name: Clean Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: '🪾 Branch to clean'
        required: true
        default: 'all'
        type: choice
        options: [all, bash, videos, websites, wget, magnets, custom]
      custom_name:
        description: '🔎 Custom branch name (only used if "custom" selected)'
        required: false
        type: string

jobs:
  clean-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Clean And Push
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if [ "${{ github.event.inputs.branch_name }}" = "custom" ]; then
            TARGET_BRANCH="${{ github.event.inputs.custom_name }}"
          else
            TARGET_BRANCH="${{ github.event.inputs.branch_name }}"
          fi

          if [ -z "$TARGET_BRANCH" ]; then
            echo "Branch name is empty"
            exit 0
          fi

          git fetch origin

          if [ "$TARGET_BRANCH" = "all" ]; then
            echo "Mode: Cleaning all remote branches except main and dev."
            git remote update origin --prune
            git branch -r | \
            sed 's|origin/||' | \
            sed 's|^[[:space:]]*||' | \
            grep -vE '^(HEAD|main|master|dev)$' | \
            while read -r branch; do
              if [ -n "$branch" ]; then
                echo "Deleting branch: $branch"
                git push origin --delete "$branch"
              fi
            done
          else
            echo "Mode: Cleaning single branch: $TARGET_BRANCH"
            if git ls-remote --exit-code --heads origin "$TARGET_BRANCH" > /dev/null 2>&1; then
              git push origin --delete "$TARGET_BRANCH"
            fi
          fi
